// <auto-generated />
namespace SanSurveyWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class exitsurveypage13modified : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(exitsurveypage13modified));
        
        string IMigrationMetadata.Id
        {
            get { return "201711170054395_exitsurveypage13modified"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
