// <auto-generated />
namespace SanSurveyWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _201707120511301_add_ExitSurvey_Page11_table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_201707120511301_add_ExitSurvey_Page11_table));
        
        string IMigrationMetadata.Id
        {
            get { return "201707130502531_201707120511301_add_ExitSurvey_Page11_table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
