// <auto-generated />
namespace SanSurveyWebApi.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_new_Job_tbales : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_new_Job_tbales));
        
        string IMigrationMetadata.Id
        {
            get { return "201706200354103_add_new_Job_tbales"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
