// <auto-generated />
namespace SANSurveyWebAPI.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class add_ProximiVisitor : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(add_ProximiVisitor));
        
        string IMigrationMetadata.Id
        {
            get { return "201808270113296_add_ProximiVisitor"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
